{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "vzdb.serviceAccountName" . }}
  labels:
{{ include "vzdb.labels" . | indent 4 }}
{{- end -}}
