apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rtdb.fullname" . }}
  labels:
{{ include "rtdb.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "rtdb.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "rtdb.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          {{- with .Values.env }}
          env:
          - name: spring.application.name
            value: {{ .name | quote }}
          - name: kdm.rtdb.host
            value: {{ include "vzdb.fullname" . }}
          - name: kdm.rtdb.port
            value: {{ .port | quote }}
          - name: kdm.rtdb.username
            value: {{ .username | quote }}
          - name: kdm.rtdb.password
            value: {{ .password | quote }}
          - name: kdm.rtdb.rule
            value: {{ .rule | quote }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}