apiVersion: v1
kind: Service
metadata:
  name: {{ include "rtdb.fullname" . }}
  labels:
{{ include "rtdb.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externallPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app: {{ include "rtdb.name" . }}
    release: {{ .Release.Name }}
